### PR TITLE
Fix for removal of whitespace in 8.9 and later

### LINKED ISSUE #6: Aruba config doesn't include spaces at the front any more
I upgraded from ArubaOS 8.7 to 8.10 and none of the encrypted passwords got removed any more. Inspecting the output, it's because `write term` doesn't include any indentation spaces, so the regexes need to be changed from `/^(\s+wpa-passphrase )/` to `/^(\s?wpa-passphrase )/` (ie `+` to `?`).

As a bonus, most (but not all!) lines contain a space at the end which ruins diffing from previous configs, where only some lines had terminal spaces before. So in WriteTerm I put this at top of the `while (<$INPUT>) {` loop
```perl
        # strip trailing whitespace
        s/ $//;
```

### PR DESCRIPTION
**Pull request by trs80**
Also remove dump-collection-profile and ifmap-cppm passwords

Fixes #6

### CODE REVIEW

File: aruba.pm [hunk 1]
```diff
@@ -469,6 +469,8 @@ sub WriteTerm {
 
 	while (<$INPUT>) {
 		tr/\015//d;
+		# strip trailing whitespace
+		s/ $//;
```
Comment (miken32) [inline aruba.pm:473]: Would it cause any problems to use `\s*` here to catch any trailing whitespace instead of just a single space?

Comment (trs80) [reply aruba.pm:473]: This one definitely needs to be ` +$` at most, I tried `\s*$` and `\s+$` and it ate all the newlines.
